using Volo.Abp;

namespace BookingAndReservationSystems.EntityFrameworkCore;

public abstract class BookingAndReservationSystemsEntityFrameworkCoreTestBase : BookingAndReservationSystemsTestBase<BookingAndReservationSystemsEntityFrameworkCoreTestModule>
{

}
