using BookingAndReservationSystems.EntityFrameworkCore;
using Xunit;

namespace BookingAndReservationSystems.EntityFrameworkCore;

public class BookingAndReservationSystemsEntityFrameworkCoreCollectionFixtureBase : ICollectionFixture<BookingAndReservationSystemsEntityFrameworkCoreFixture>
{

}
